host: 10.10.10.10
port: 22
username: root
password: 123456
upload:
  remote-path: /home/upload-test/
  file:
    - local-path: ./test.txt # 本地文件的路径
      # 服务器上想使用的名字 一般与源文件相同
      remote-file: test.txt
      cmd: sh /home/upload-test/restart-image.sh